version: 2
updates:
  - package-ecosystem: "devcontainers" # See documentation for possible values
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"